replicaCount: 1

image:
  repository: containerum/auth
  tag: v1.0.0
  pullPolicy: Always
  secret:

service:
  externalIP:
  http:
    port: 1111
    targetPort: 1111
  grpc:
    port: 1112
    targetPort: 1112

volumeMounts:
  name: auth-volume
  mountPath: '/storage'

volume:
  name: auth-volume
  empty:
    emptyDir: {}
  gluster:
    glusterfs:
      endpoints: glusterfs
      path: sys_gv_hosting_ch-auth
      readOnly: false

configMap:
  name: jwt-key
  jwtKey: nhJRaMxdg7L7YYxM+PBKzF1q/75RIjqbU+gr2qj2TPY=
  mountPath: '/keys'

env:
  CH_AUTH_HTTP_LISTENADDR: 0.0.0.0:1111
  CH_AUTH_GRPC_LISTENADDR: 0.0.0.0:1112
  CH_AUTH_LOG_MODE: text
  CH_AUTH_LOG_LEVEL: 4
  CH_AUTH_TOKENS: jwt
  CH_AUTH_JWT_SIGNING_METHOD: HS256
  CH_AUTH_ISSUER: containerum.com
  CH_AUTH_ACCESS_TOKEN_LIFETIME: 15m
  CH_AUTH_REFRESH_TOKEN_LIFETIME: 48h
  CH_AUTH_JWT_SIGNING_KEY_FILE: /keys/jwt.key
  CH_AUTH_JWT_VALIDATION_KEY_FILE: /keys/jwt.key
  CH_AUTH_STORAGE: buntdb
  CH_AUTH_BUNT_STORAGE_FILE: /storage/storage.db
  CH_AUTH_TRACER: zipkin
  CH_AUTH_ZIPKIN_COLLECTOR: nop
