[prune]
    non-go = true
    go-tests = true
    unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  name = "github.com/mssola/user_agent"
  version = "0.4.1"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  version = "0.3.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/buntdb"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.8.2"

[[constraint]]
  version = "~0.2.0"
  name = "git.containerum.net/ch/kube-client"

[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/json-types"

[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/utils"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.12.0"

[[constraint]]
  name = "github.com/go-playground/locales"
  version = "0.11.2"
