[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "git.containerum.net/ch/api-gateway"
    non-go = false

  [[prune.project]]
    name = "git.containerum.net/ch/utils"
    non-go = false

  [[prune.project]]
      name = "git.containerum.net/ch/cherry"
      non-go = false

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  name = "github.com/mssola/user_agent"
  version = "0.4.1"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  version = "0.3.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/buntdb"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.11.0"

[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/utils"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.12.0"

[[constraint]]
  name = "github.com/go-playground/locales"
  version = "0.11.2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "~1.2.0"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/api-gateway"

[[constraint]]
  name = "git.containerum.net/ch/cherry"
  version = "~1.0.1-rc2"
