swagger: "2.0"
parameters:
  UserIDHeader:
    name: X-User-ID
    in: header
    type: string
    format: uuid
    required: true
  FingerprintHeader:
    name: X-User-Client
    in: header
    type: string
    required: true
  UserAgentHeader:
    name: X-User-Agent
    in: header
    type: string
    required: true
  ClientIPHeader:
    name: X-Client-IP
    in: header
    type: string
    format: ip
    required: true
  UserRoleHeader:
    name: X-User-Role
    in: header
    type: string
    enum:
      - user
      - admin
    required: true
  PartTokenIDHeader:
    name: X-Part-Token-ID
    in: header
    type: string
    format: uuid
    required: false
