swagger: "2.0"
parameters:
  UserIDHeader:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/UserIDHeader"
  FingerprintHeader:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/UserClientHeader"
  UserAgentHeader:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/UserAgentHeader"
  ClientIPHeader:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/ClientIPHeader"
  UserRoleHeader:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/UserRoleHeader"
responses:
  error:
    description: cherry error
    schema:
      $ref: "vendor/github.com/containerum/cherry/swagger.json#/definitions/Err"
