apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
data:
  {{ if .Values.env.local.JWT_KEY }}
  jwt.key: {{ .Values.env.local.JWT_KEY | quote }}
  {{ else }}
  jwt.key: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
